# Generated by Django 5.0 on 2024-01-13 01:47

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_workspace_note_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=django_bleach.models.BleachField(),
        ),
    ]
